version: '3.7'
services:
  rasa:
    image: rasa:1.10.16
    expose:
      - 5005
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: pi/ms_pocketsphinx:rasa_actions 
    expose:
      - 5055
