version: '3.0'
services:
  rasa:
    image: rasa/rasa:2.0.3-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: rasa-action-server:latest
    expose: 
      - "5055"