version: '3.3'
services:
  rasa:
    image: hoomant/mamasara:mamasara_rasa
    expose:
      - 5005
    ports:
      - 5005:5005
    volumes:
      - ./rasa/:/app
    network_mode: host
    command:
      - run
