language: en
pipeline:
- name: WhitespaceTokenizer
- name: CRFEntityExtractor
- name: CountVectorsFeaturizer
  OOV_token: oov
  token_pattern: (?u)\b\w+\b
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: EmbeddingIntentClassifier
  epochs: 50
  loss_type: margin
- name: EntitySynonymMapper
policies:
- name: EmbeddingPolicy
  max_history: 10
  epochs: 20
  batch_size:
  - 32
  - 64
- name: AugmentedMemoizationPolicy
- name: FallbackPolicy
  nlu_threshold: 0.6
  core_threshold: 0.3
  fallback_action_name: action_default_fallback
- name: FormPolicy
- name: MappingPolicy
